name: deploy
on: 
  push:
    branches:
      - main
jobs: 
  deploy_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install kubectl cli
      uses: azure/setup-kubectl@v3   
    
    - name: Set Kubeconfig
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: get pods
      
      #uses: azure/k8s-set-context@v4
      #with:
      # kubeconfig: ${{ secrets.KUBE_CONFIG }}
      
    - name: Deploy manifests
      run: |
        kubectl apply -f k8s-specifications/
