name: deploy
on: 
  push:
    branches:
      - main
jobs: 
  deploy_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install kubectl cli
      uses: azure/setup-kubectl@v3
      with: 
        version: 'v1.31.0'  
    
    - name: Set Kubeconfig
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}
    
    - name: Check files
      run: |
        cat k8s-specifications/*.yaml

    - name: Deploy manifests
      run: |
        kubectl apply -f k8s-specifications/vote-deployment.yaml --validate=false -v=8
